blog/urls.py
from django.urls import path
from .views import BlogListView, BlogCreateView, BlogDeleteView, UserBlogListView
from . import views

urlpatterns = [
    path('', BlogListView.as_view(), name='blog-index'),
    path('blog/<int:pk>/', views.blog_view, name='blog-detail'),
    path('blog/new/', BlogCreateView.as_view(), name='blog-create'),
    path('blog/<int:pk>/delete', BlogDeleteView.as_view(), name='blog-delete'),
    path('user/<str:username>', UserBlogListView.as_view(), name='user-blogs'),
    path ('about/', views.about, name='blog-about')
]

bubble/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from user import views as user_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('signup/', user_views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='user/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='user/logout.html'), name='logout'),
    path('pw-reset/', auth_views.PasswordResetView.as_view(template_name='user/password_reset.html'), name='pw-reset'),
    path('pw-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='user/password_reset_done.html'), name='password_reset_done'),
    path('pw-reset/confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='user/password_reset_confirm.html'), name='password_reset_confirm'),
    path('pw-reset/complete', auth_views.PasswordResetCompleteView.as_view(), name="password_reset_complete"),
    path('profile/', user_views.profile, name='profile'),
    path('', include('blog.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse

class Blog(models.Model):
    content = models.CharField(max_length=200)
    date = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    parent = models.ForeignKey('Blog', on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return self.content
    
    def get_absolute_url(self):
        return reverse("blog-detail", kwargs={"pk": self.pk})
    

user/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='default.jpg', upload_to='profile_pics')

    def __str__(self):
        return f'{self.user.username} Profile'
    
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        img = Image.open(self.image.path)

        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)

blog/forms.py
from django import forms
from .models import Blog

class BlogResponseForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields = ['content']

user/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile

class UserSigninForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email']

class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['image']

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import User
from django.views.generic import ListView, CreateView, DeleteView
from .models import Blog
from .forms import BlogResponseForm


def index(request):
    context = {
        'blogs': Blog.objects.all()
    }
    return render(request, 'blog/index.html', context)


class BlogListView(ListView):
    model = Blog
    template_name = 'blog/index.html'
    context_object_name = 'blogs'

    def get_queryset(self):
        return Blog.objects.order_by('-date').filter(parent=None)

class UserBlogListView(ListView):
    model = Blog
    template_name = 'blog/user_blog.html'
    context_object_name = 'blogs'

    def get_queryset(self):
        user = get_object_or_404(User, username=self.kwargs.get('username'))
        return Blog.objects.order_by('-date').filter(author=user)

def blog_view(request, pk):
    if request.method == 'POST':
        form = BlogResponseForm(request.POST)
        form.instance.author = request.user
        form.instance.parent = get_object_or_404(Blog, id=pk)
        if form.is_valid():
            form.save()
    else:
        form = BlogResponseForm()
    
    context = {
        'object': Blog.objects.get(id=pk),
        'form': form,
        'responses': Blog.objects.order_by('date').filter(parent=pk)
    }
    return render(request, "blog/blog_detail.html", context)

class BlogCreateView(LoginRequiredMixin, CreateView):
    model = Blog
    fields = ['content']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)
    
class BlogDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Blog
    success_url = '/'

    def test_func(self):
        blog = self.get_object()
        if self.request.user == blog.author:
            return True
        return False

def about(request):
    return render(request, 'blog/about.html', context={'title': 'About'})

user/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import UserSigninForm, UserUpdateForm, ProfileUpdateForm

def signup(request):
    if request.method == 'POST':
        form = UserSigninForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Thanks for signing up {username}, you can now login!')
            return redirect('login')
    else:
        form = UserSigninForm()
    context = {
        'form': form
    }
    return render(request, 'user/signup.html', context)


@login_required
def profile(request):
    if request.method == 'POST':
        user_update_form = UserUpdateForm(request.POST, instance=request.user)
        profile_update_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)
        if user_update_form.is_valid() and profile_update_form.is_valid():
            user_update_form.save()
            profile_update_form.save()
            messages.success(request, f'Your profile has been updated!')
            return redirect('profile')        
    else:
        user_update_form = UserUpdateForm(instance=request.user)
        profile_update_form = ProfileUpdateForm(instance=request.user.profile)

    context = {
        'user_update_form': user_update_form,
        'profile_update_form': profile_update_form
    }

    return render(request, 'user/profile.html', context)

blog/templates/blog/about.html
{% extends "blog/base.html" %}
{% block content %}
    <h1>About!</h1>
    <script>
        document.getElementById("about").classList.add("active")
    </script>
{% endblock content %}

blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html data-bs-theme="light">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% if title %}
    <title>{{ title }}</title>
    {% else %}
    <title>Bubble</title>
    {% endif %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'blog/main.css'%}">
</head>
<body>
<header>
    <nav class=" container-fluid navbar navbar-expand-lg border-bottom mb-2">
        <div class="container">
            <a class="navbar-brand" href="/"><img class="profile-picture grow" src="{% static 'new_bubble.png' %}" alt=""></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a id="home" class="nav-link" href="{% url 'blog-index' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a id="about" class="nav-link" href="{% url 'blog-about' %}">About</a>
                    </li>
                    {% if user.is_authenticated %}
                        <li>
                            <a id="profile" class="nav-link" href="{% url 'profile' %}">Profile</a>
                        </li>
                        <li class="nav-item">
                            <a id="logout" class="nav-link" href="{% url 'logout' %}">Logout</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a id="login" class="nav-link" href="{% url 'login' %}">Login</a>
                        </li>
                        <li class="nav-item">
                            <a id="signup" class="nav-link" href="{% url 'signup' %}">Sign up</a>
                        </li>
                    {% endif %}
                    <!--
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Dropdown
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="#">Action</a></li>
                            <li><a class="dropdown-item" href="#">Another action</a></li>
                            <li><hr class="dropdown-divider"></li>
                            <li><a class="dropdown-item" href="#">Something else here</a></li>
                        </ul>
                    </li>
                    -->
                    <!--
                    <li class="nav-item">
                        <a class="nav-link disabled">Disabled</a>
                    </li>
                    -->
                </ul>
                <!--
                <form class="d-flex" role="search">
                    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-primary" type="submit">Search</button>
                </form>
                -->
                <button id="mode" class="btn btn-outline-dark">Light</button>
            </div>
        </div>
    </nav>
</header>
<main class="container">
    <div class="row">
        <div class="d-flex flex-column col-md-8 align-items-center">
            {% if messages %}
            {% for msg in messages %}
                <div class="alert alert-{{msg.tags}}">{{ msg }}</div>
            {% endfor %}
            {% endif %}
            {% block content %}{% endblock %}
        </div>
        <div class="d-none d-md-block col-md-3">
            <div class="sticky-top pb-3">
                <div class="card-body text-center mt-3">
                    <h3>trending</h3>
                    <ul class="list-group">
                        <li class="list-group-item">Silicon Valley Bank</li>
                        <li class="list-group-item">War in Ukraine</li>
                        <li class="list-group-item">UK Strikes</li>
                        <li class="list-group-item">Why aren't you using bubble?</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    
</main>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
<script>
    const mode = document.getElementById('mode')
    const theme = localStorage.getItem('theme')
    
    const setTheme = theme => {
        localStorage.setItem('theme', theme)
        document.documentElement.setAttribute('data-bs-theme', theme)
        mode.className = ""
        mode.classList.add('btn')
        mode.classList.add(`btn-outline-${notTheme(theme)}`)
        mode.textContent = notTheme(theme)

    }

    const notTheme = (theme) => {
        if (theme == 'light') {
            return 'dark'
        } else {
            return 'light'
        }
    }

    if (theme) {
        setTheme(theme)
    }

    mode.addEventListener('click', () => {
        const theme = localStorage.getItem('theme')
        if (theme == 'light') {
            setTheme('dark')

        } else {
            setTheme('light')
        }
    })

    
</script>
</body>
</html>

blog/templates/blog/blog_confirm_delete.html
{% extends 'blog/base.html' %}
{% block content  %}
<div>
    <form method="POST">
        {% csrf_token %}
        <fieldset>
            <legend>Delete blog?</legend>
        </fieldset>
        <div>
            <button class="btn btn-outline-danger">Delete</button>
            <a class="btn btn-outline-secondary" href="{% url 'blog-detail' object.id %}">Cancel</a>
        </div>
    </form>
</div>
{% endblock content  %}

blog/templates/blog/blog_detail.html
{% extends 'blog/base.html' %}
{% block content %}
<div class="col-md-8">
    <div class="d-flex flex-row my-2 p-2" href="{% url 'blog-detail' object.id %}">
        <div class="d-flex flex-column align-items-center justify-content-center me-2">
            <img class="profile-picture" src="{{ object.author.profile.image.url }}" alt="" >
        </div>
        <div class="fs-6 lh-sm ">
            <span class="fs-5 text-muted"><a href="{% url 'user-blogs' object.author.username %}">{{object.author}}</a> - {{object.date}}</span>
            <p class="m-0 fs-4">{{object.content}}</p>
        </div>
    </div>
    {% if object.author == user %}
        <a class="btn btn-outline-danger" href="{% url 'blog-delete' object.id %}">Delete</a>
    {% endif %}
    {% if user.is_authenticated %}
    <div class="mt-3 mb-2 border-top border-bottom py-2">
        <form method="POST">
            {% csrf_token %}
            <fieldset>
                <label class="form-label" for="id_content">Reply to {{object.author.username}}</label>
                <input type="text" class="text-input form-control" type="text" maxlength="200" id="id_content" name="content" placeholder="Type reply here">
            </fieldset>
            <div class="mt-3">
                <button class="btn btn-outline-info" type="submit">Submit</button>
            </div>
        </form>
    </div>
    {% endif %}
    <div>
        {% for response in responses %}
            {% include "blog/blog_list.html" with blog=response %}
        {% endfor %}
    </div>
</div>

{% endblock content %}

blog/templates/blog/blog_form.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}
{% block content  %}
<div class="col-md-8">
    <form method="POST">
        {% csrf_token %}
        <fieldset>
            <legend></legend>
            {{ form|crispy }}
        </fieldset>
        <div>
            <button class="btn btn-outline-info" type="submit">Save</button>
        </div>
    </form>
    <script>
        document.getElementById("new-blog").classList.add("active")
    </script>
</div>
{% endblock content  %}

blog/templates/blog/blog_list.html
<a class="d-flex flex-row my-2 p-2 blog text-reset text-decoration-none" href="{% url 'blog-detail' blog.id %}">
    <div class="d-flex flex-column align-items-center justify-content-center me-2">
        <img class="profile-picture" src="{{ blog.author.profile.image.url }}" alt="" >
    </div>
    <div class="fs-6 lh-sm">
        <span class="text-muted">{{blog.author}}</span>
        <p class="m-0">{{blog.content}}</p>
    </div>
</a>

blog/templates/blog/index.html
{% extends "blog/base.html" %}
{% block content %}
<div class="col-md-8">
    {% if user.is_authenticated %}
    <div class="mb-2 border-bottom py-2">
        <form method="POST" action="{% url 'blog-create'%}">
            {% csrf_token %}
            <fieldset>
                <label class="form-label" for="id_content">Post your thoughts!</label>
                <input type="text" class="text-input form-control" type="text" maxlength="200" id="id_content" name="content" placeholder="Thoughts go here">
            </fieldset>
            <div class="mt-2">
                <button class="btn btn-outline-info" type="submit">Submit</button>
            </div>
        </form>
    </div>{% endif %}
    {% for blog in blogs %}
         {% include "blog/blog_list.html" with blog=blog %}
    {% endfor %}
</div>
<script>
    document.getElementById("home").classList.add("active")
</script>
{% endblock content %}

blog/templates/blog/user_blog.html
{% extends 'blog/base.html' %}
{% block content %}
    <div>
        <h1>{{ blogs.first.author }}</h1>
        {% for blog in blogs  %}
            {% include "blog/blog_list.html" with blog=blog %}
        {% endfor %}
    </div>
{% endblock content %}

user/templates/user/login.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="col-md-4">
        <form method="POST">
            {% csrf_token %}
            <fieldset>
                <legend class="border-bottom mb-4">Log in!</legend>
                {{ form|crispy  }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-primary" type="submit">Login</button>
            </div>
        </form>
        <div>
            <small class="text-muted">
                Need an account? <a class="ml-2" href="{% url 'signup' %}">Sign up!</a>
            </small>
        </div>
    </div>
    <script>
        document.getElementById("login").classList.add("active")
    </script>
{% endblock content %}

user/templates/user/logout.html
{% extends "blog/base.html" %}
{% block content %}
    <div>
        <h2>You've been logged out!</h2>
        <div>
            <small class="text-muted">
                <a href="{% url 'login' %}">Sign back in?</a>
            </small>
        </div>
    </div>
    <script>
        document.getElementById("logout").classList.add("active")
    </script>
{% endblock content %}

user/templates/user/password_reset.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div>
        <form method="POST">
            {% csrf_token %}
            <fieldset>
                <legend class="border-bottom mb-4">Reset password</legend>
                {{ form|crispy  }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-primary" type="submit">Request password reset</button>
            </div>
        </form>
    </div>
{% endblock content %}

user/templates/user/password_reset_confirm.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div>
        <form method="POST">
            {% csrf_token %}
            <fieldset>
                <legend class="border-bottom mb-4">Reset password?</legend>
                {{ form|crispy  }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-primary" type="submit">Reset</button>
            </div>
        </form>
    </div>
{% endblock content %}

user/templates/user/password_reset_done.html
{% extends "blog/base.html" %}
{% block content %}
    <div class="alert alert-info">
        Check your email!
    </div>
{% endblock content %}

user/templates/user/profile.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="col-md-8">
    <div class="d-flex">
        <div class="flex-shrink-0">
            <img src="{{ user.profile.image.url }}" alt="" width="100" height="100">
        </div>
        <div class="flex-grow-1 ms-3">
            <h3> {{ user.username }} </h3>
            <p> {{ user.email }} </p>
        </div>
    </div>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <fieldset class>
            <legend>My Profile</legend>
            {{ user_update_form|crispy }}
            {{ profile_update_form|crispy }}
        </fieldset>
        <div>
            <button class="btn btn-outline-primary">Update</button>
        </div>
    </form>
</div>
<script>
    document.getElementById("profile").classList.add("active")
</script>
{% endblock content%}

user/templates/user/signup.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="col-md-8">
        <form method="POST">
            {% csrf_token %}
            <fieldset>
                <legend class="border-bottom mb-4">Sign up!</legend>
                {{ form|crispy  }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-primary" type="submit">Sign up</button>
            </div>
        </form>
        <div>
            <small class="text-muted">
                Have an account? <a class="ml-2" href="{% url 'login' %}">Sign in!</a>
            </small>
        </div>
    </div>
    <script>
        document.getElementById("signup").classList.add("active")
    </script>
{% endblock content %}